#!/usr/bin/env bash

cwd=`pwd`
package=`basename $cwd`
version=`git describe --tags --dirty=M 2>/dev/null`

echo "// Code generated by go generate; DO NOT EDIT." > version.go
echo "" >> version.go
echo "package $package" >> version.go
echo "" >> version.go
echo "// Version contains the current version number of this library." >> version.go
echo "const Version = \"$version\"" >> version.go
