#!/usr/bin/env bash

cwd=`pwd`
package=`basename $cwd`
license=`cat LICENSE`

echo "// Code generated by go generate; DO NOT EDIT." > license.go
echo "" >> license.go
echo "package $package" >> license.go
echo "" >> license.go
echo "// License contains the license text of this library." >> license.go
echo "const License = \`$license\`" >> license.go
